name: board
description: "A Cross platfrom team drawing app"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  pinput: ^5.0.0
  canvas_repository: 
    path: './packages/canvas_repository'
  board_repository: 
    path: './packages/board_repository'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
