name: board_api
description: "The interface for all board related API calls."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  json_annotation: ^4.9.0
  freezed: ^2.5.2

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.8.0
  test: ^1.21.4
